import {
  Activity,
  AppWindow,
  Boxes,
  Building2,
  ChartNoAxesCombined,
  CloudUpload,
  CreditCard,
  Gauge,
  GitBranch,
  LayoutDashboard,
  ListTree,
  MonitorDot,
  MousePointerClick,
  Network,
  Package,
  Plug,
  Route,
  Scale,
  ScrollText,
  Settings,
  ShieldCheck,
  TableProperties,
  TriangleAlert,
  Truck,
  UserCircle,
  Users,
  Webhook,
  type LucideIcon,
} from 'lucide-react';

/** Ánh xạ key điều hướng (access policy) sang icon; dùng chung cho Sidebar + Topbar search. */
export const NAV_ICONS: Record<string, LucideIcon> = {
  admin_tenants: Building2,
  admin_carriers: Network,
  subscription_plans: CreditCard,
  platform_health: Activity,
  admin_audit_trail: ScrollText,
  api_traffic_logs: Route,
  system_observability: MonitorDot,
  webhook_delivery_logs: Webhook,
  quota_management: Gauge,
  dashboard: LayoutDashboard,
  orders: Package,
  inventory: Boxes,
  rules: GitBranch,
  shipments: Truck,
  reconciliation: Scale,
  analytics: ChartNoAxesCombined,
  carrier_connections: Plug,
  staff_accounts: Users,
  roles_permissions: ShieldCheck,
  general: Settings,
  webhooks: Webhook,
  usage: CreditCard,
  audit_trail: ScrollText,
  integration_errors: TriangleAlert,
  profile: UserCircle,
  components: AppWindow,
  data_table: TableProperties,
  buttons: MousePointerClick,
  dropzone: CloudUpload,
  data_display: ListTree,
};
