import {
  Activity,
  Archive,
  ArrowDownToLine,
  AppWindow,
  Boxes,
  Building2,
  ChartNoAxesCombined,
  ClipboardCheck,
  ClipboardList,
  CloudUpload,
  CreditCard,
  FileSpreadsheet,
  Gauge,
  GitBranch,
  KeyRound,
  LayoutDashboard,
  ListTree,
  MonitorDot,
  MousePointerClick,
  Network,
  Package,
  PackageCheck,
  PackageSearch,
  Plug,
  RotateCcw,
  Route,
  Scale,
  ScrollText,
  Settings,
  TableProperties,
  TriangleAlert,
  Truck,
  UserCircle,
  Users,
  Webhook,
  Warehouse as WarehouseIcon,
  type LucideIcon,
} from 'lucide-react';

/** Ánh xạ key điều hướng (access policy) sang icon; dùng chung cho Sidebar + Topbar search. */
export const NAV_ICONS: Record<string, LucideIcon> = {
  platform_staff: Users,
  admin_tenants: Building2,
  admin_carriers: Network,
  subscription_plans: CreditCard,
  platform_health: Activity,
  admin_audit_trail: ScrollText,
  api_traffic_logs: Route,
  system_observability: MonitorDot,
  webhook_delivery_logs: Webhook,
  quota_management: Gauge,
  dashboard: LayoutDashboard,
  orders: Package,
  skus: Package,
  asns: ClipboardList,
  returns: RotateCcw,
  statements: FileSpreadsheet,
  warehouses: WarehouseIcon,
  admin_warehouses: WarehouseIcon,
  exceptions: TriangleAlert,
  warehouse_inbound: ArrowDownToLine,
  warehouse_receiving: PackageCheck,
  warehouse_putaway: Archive,
  warehouse_picking: PackageSearch,
  warehouse_packing: Package,
  warehouse_handover: Truck,
  warehouse_returns: RotateCcw,
  warehouse_counts: ClipboardCheck,
  inventory: Boxes,
  rules: GitBranch,
  shipments: Truck,
  reconciliation: Scale,
  analytics: ChartNoAxesCombined,
  carrier_connections: Plug,
  api_keys: KeyRound,
  staff_accounts: Users,
  general: Settings,
  seller_profile: Building2,
  webhooks: Webhook,
  usage: CreditCard,
  audit_trail: ScrollText,
  integration_errors: TriangleAlert,
  profile: UserCircle,
  components: AppWindow,
  data_table: TableProperties,
  buttons: MousePointerClick,
  dropzone: CloudUpload,
  data_display: ListTree,
};
